<form class="card" data-group="interior" autocomplete="off">
    <?= $this->field()->hidden('interior[id]', $interior->getId()); ?>
    <?= $this->field()->hidden('interior[wallpaper_id]', $interior->getWallpaperId()); ?>
    <?= $this->field('Order')->text('interior[order]', $interior->getOrder(), ['class' => 'form-control']); ?>

    <?php if ($interior->getFilename()): ?>
    <div class="mt-2 mb-2">
        <img class="img-fluid" src="<?= $interior->getFilename(); ?>" />
    </div>
    <?php endif; ?>

    <?= $this->field('Image file')->fileData('interior[filename]', $interior->getFilename(), 'image/jpeg', ['class' => 'form-control']); ?>

    <?php $this->loadPartial('actions', [
        'new' => !$interior->getId(),
        'add' => ['Wallpaper:Admin:Interior@addAction', $interior->getWallpaperId()],
        'edit' => 'Wallpaper:Admin:Interior@editAction',
        'save' => 'Wallpaper:Admin:Interior@saveAction',
        'cancel' => ['Wallpaper:Admin:Wallpaper@editAction', $interior->getWallpaperId()]
    ]); ?>
</form>