<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

?>

<form class="card" data-group="room" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#hotel-room-active" role="tab" data-toggle="tab"><i class="fas fa-hotel"></i> <?php $this->show('Wallpaper'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#hotel-room-configuration" role="tab" data-toggle="tab"><i class="fas fa-dice"></i> <?php $this->show('Configuration'); ?></a></li>
        <?php if (!$isNew): ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#wall-interior" role="tab" data-toggle="tab"><i class="fas fa-camera-retro"></i> <?php $this->show('Interior'); ?> <small class="text-muted">(<?= count($interiors); ?>)</small></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#wall-gallery" role="tab" data-toggle="tab"><i class="fas fa-image"></i> <?php $this->show('Gallery'); ?> <small class="text-muted">(<?= count($images); ?>)</small></a></li>
        <?php endif; ?>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="hotel-room-active" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade in <?= $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $wallpaper); ?>
                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <?= $this->field()->hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= $this->field()->hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                    <?= $this->field()->hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?= $this->field('Name')->text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control']); ?>
                    <?= $this->field('Description')->textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['class' => 'form-control']); ?>

                    <div class="options">
                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'placeholder' => $this->translate('URL slug for this room. By default is taken from the name'))); ?>

                                    <span class="input-group-addon">
                                        <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <?= $this->field('Change frequency')->select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), ['class' => 'form-control']); ?>
                        <?= $this->field('Priority')->select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), ['class' => 'form-control']); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Room title'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <?= $this->field('Keywords')->text(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), ['class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines')]); ?>
                        <?= $this->field('Description')->textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), ['class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines')]); ?>
                    </div>                    
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="tab-pane fade" id="hotel-room-configuration" role="tabpanel">
            <?= $this->field()->hidden('wallpaper[id]', $entity->getId()); ?>
            <?= $this->field('SKU')->number('wallpaper[sku]', $entity->getSku(), ['class' => 'form-control']); ?>
            <?= $this->field('Companions')->select('companions[]', $companions, $companionIds, ['class' => 'form-control', 'multiple' => true]); ?>
        </div>

        <?php if (!$isNew): ?>
        <div class="tab-pane fade" id="wall-interior" role="tabpanel">
            <p><a class="btn btn-primary" href="<?= $this->url('Wallpaper:Admin:Interior@addAction', [$id]); ?>"><?= $this->translate('Upload new interior'); ?></a></p>

            <div class="table-responsive">
                <?= $this->widget(new GridViewWidget($interiors, [
                    'tableClass' => 'table table-hover table-bordered',
                    'columns' => [
                        [
                            'column' => 'filename',
                            'value' => function($interior){
                                return Element::image($interior->getFilename(), ['class' => 'img-fluid w-50']);
                            },
                            'attributes' => [
                                'class' => null
                            ]
                        ],

                        [
                            'column' => 'Primary',
                            'value' => function($interior) use ($entity){
                                return Element::radio('wallpaper[interior_id]', $interior->getId(), $entity->getInteriorId() == $interior->getId());
                            },
                            'attributes' => [
                                'class' => 'text-center'
                            ]
                        ]
                    ],

                    'actions' => [
                        function($interior){
                            return Icon::edit(
                                $this->url('Wallpaper:Admin:Interior@editAction', $interior->getId()),
                                $this->translate('Edit this interior')
                            );
                        },

                        function($interior){
                            return Icon::remove(
                                $this->url('Wallpaper:Admin:Interior@deleteAction', $interior->getId()), 
                                $this->translate('Remove this interior')
                            );
                        }
                    ]
                ])); ?>
            </div>
        </div>

        <div class="tab-pane fade" id="wall-gallery" role="tabpanel">
            <p><a class="btn btn-primary" href="<?= $this->url('Wallpaper:Admin:Gallery@addAction', [$id]); ?>"><?= $this->translate('Upload new image'); ?></a></p>

            <div class="table-responsive">
                <?= $this->widget(new GridViewWidget($images, [
                    'tableClass' => 'table table-hover table-bordered',
                    'columns' => [
                        [
                            'column' => 'filename',
                            'value' => function($image){
                                return Element::image($image->getFilename(), ['class' => 'img-fluid w-50']);
                            },
                            'attributes' => [
                                'class' => null
                            ]
                        ],

                        [
                            'column' => 'color_name',
                            'attributes' => [
                                'class' => 'text-center'
                            ]
                        ],
                        
                        [
                            'column' => 'sku',
                            'label' => 'SKU'
                        ]
                    ],

                    'actions' => [
                        function($image){
                            return Icon::edit(
                                $this->url('Wallpaper:Admin:Gallery@editAction', $image->getId()),
                                $this->translate('Edit this image')
                            );
                        },

                        function($image){
                            return Icon::remove(
                                $this->url('Wallpaper:Admin:Gallery@deleteAction', $image->getId()), 
                                $this->translate('Remove this image')
                            );
                        }
                    ]
                ])); ?>
            </div>
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$entity->getId(),
        'add' => 'Wallpaper:Admin:Wallpaper@addAction',
        'edit' => 'Wallpaper:Admin:Wallpaper@editAction',
        'save' => 'Wallpaper:Admin:Wallpaper@saveAction',
        'cancel' => 'Wallpaper:Admin:Wallpaper@indexAction',
        'options' => true
    ]); ?>
</form>
